### ISSUE TITLE
Can we watch the S3 filesystem for changes?

### ISSUE THREAD

**Issue by rutgerfarry** [osu-cass/smarter-balanced-item-viewer#11]
We need to know if files change in our S3 buckets so the changed items can be indexed.

**Comment by Garrett-S** [comment]
Amazon supports publishing message when an object is created or removed. The notification can be sent to their queue service which we can poll, or their notification service which sends push notifications. We can consume these notifications to update the index as needed.  
##### Notifications
[Amazon Notifications](http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html#supported-notification-event-types)  
[Amazon Queue Service](https://aws.amazon.com/sqs/)
[Amazon Notification Service](https://aws.amazon.com/sns/)

**Comment by rutgerfarry** [comment]
Sounds good. I liked your idea of polling for updates every few seconds. Since uploads are likely to be very infrequent however (I imagine months with no uploads), perhaps we could consider notifications as well.
