### ISSUE TITLE
Instance specific vs. overall diagnostics

### ISSUE THREAD

**Issue by Garrett-S** [osu-cass/smarter-balanced-item-viewer#32]
Should the diagnostic API return instance specific diagnostics, or an average of all of the instances?

**Comment by Garrett-S** [comment]
We are currently reporting instance specific diagnostics.

**Comment by alexlepinski** [comment]
We need a localstatus that returns the individual node status.  /status?level={1-5} will return status for all nodes within the ec2 group

**Comment by Garrett-S** [comment]
This has been addressed in #57
