### ISSUE TITLE
Diagnostics API needs to check user home read/write permissions

### ISSUE THREAD

**Issue by Garrett-S** [osu-cass/smarter-balanced-item-viewer#38]
The Diagnostics API level 4 needs to check that the user running the application has read and write permissions on their home directory so the application has a place to temporarily download the  content packages.

**Comment by alexlepinski** [comment]
Do we need to do this still?  Builder will give item viewer service content

**Comment by Garrett-S** [comment]
The level 4 diagnostic is checking for data write. We don't have a case where we are writing data that I am aware of so it can probably be removed.

**Comment by Garrett-S** [comment]
Due to the changes in the way we are doing content updates this is no longer an issue.
