### ISSUE TITLE
Print support for IRIS

### ISSUE THREAD

**Issue by alexlepinski** [osu-cass/smarter-balanced-item-viewer#51]
http://itemviewerservice.cass.oregonstate.edu/item/187-2659?isaap=TDS_PoD_Item

Enable codes for PrintOnDemand

**Comment by alexlepinski** [comment]
Can we do this easily? I believe we don't have some style sheets from student

**Comment by Garrett-S** [comment]
What exactly is the print on demand option supposed to do? Does it change the formatting on the item to make it printer friendly? I need to research this some more.

**Comment by Garrett-S** [comment]
I poked around in Student and Iris. The buttons that do something (zoom, dictionary, calculator, etc.) all have JavaScript associated with them in the shared blackbox. I need to find where the printer JS lives.

I'm also unclear on how exactly printing works in Student. One of the help pages in Student has the text: "To print a question, click the printer icon for that question. Your print request will be sent to your TA for approval." Does the TA print the question, or is it printed normally after approval? This merits further investigation if I can find the scripts.

**Comment by Garrett-S** [comment]
It looks like this is on hold for now. I tagged it with future because we will probably be revisiting it at a later date.
